#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_regex='^(((feat|fix|refactor|chore): #[0-9]+)|Merge|version)'
error_msg="Aborting commit. Your commit message should follow '(feat|fix|refactor|chore): #000 description' pattern or be a Merge"

if ! grep -qE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
