#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

command_exists nvm || {
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}
command_exists nvm && nvm use

yarn lint-staged
